[package]
name = "ment_os"
version = "0.1.0"
edition = "2021"
authors = ["H-Chris233"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
volatile = "0.6.1"

